### ISSUE TITLE
Automatic data collection system

### ISSUE THREAD

**Issue by ValterAro** [buerokratt/Common-Knowledge#1]
AS A product manager
I WANT TO have an automatic system for retrieving data
SO THAT data can be collected without manual interference

AC:

- [ ] Possibility to add and configure new API connections #2 
- [ ] Possibility to add new websites for scraping #3 
- [ ] Metadata should be added to each file showing when the data was acquired and from where #4 
- [ ] Data should be automatically uploaded to the specified data storage [Storage ADR](https://github.com/buerokratt/Buerokratt-onboarding/blob/main/Architectural-Decision-Records-ADR/data-pipelines/09.%20storage.md)

_For automated renewal_
- [ ]  The technical solution should use CronManager (https://github.com/buerokratt/CronManager) for triggering periodical work?
- [ ] When downloading, data source must be compared to the allready retrieved file from the same data source in the data storage. Data will be processed only in case there are any changes in the data.
- [ ] The period of data renewal is adjustablea according to https://github.com/buerokratt/Common-Knowledge/issues/7
